import { z } from 'zod';
export const EstimateRow = z.object({
  現場コード: z.string(),
  見積番号: z.string(),
  見積日: z.string(),
  行番号: z.coerce.number(),
  分類: z.string().optional(),
  品番: z.string().optional(),
  品名: z.string(),
  規格: z.string().optional(),
  数量: z.coerce.number(),
  単位: z.string(),
  '原価単価(税抜)': z.coerce.number().optional(),
  '販売単価(税抜)': z.coerce.number(),
  '税率(%)': z.coerce.number().optional(),
  備考: z.string().optional(),
});
export const PORow = z.object({
  現場コード: z.string(),
  発注番号: z.string(),
  発注日: z.string(),
  発注先コード: z.string(),
  発注先名: z.string().optional(),
  行番号: z.coerce.number(),
  分類: z.string().optional(),
  品番: z.string().optional(),
  品名: z.string(),
  数量: z.coerce.number(),
  単位: z.string(),
  '仕入単価(税抜)': z.coerce.number(),
  '税率(%)': z.coerce.number().optional(),
  納期: z.string().optional(),
  備考: z.string().optional(),
});
export const BillRow = z.object({
  発注番号: z.string(),
  仕入請求番号: z.string(),
  請求日: z.string(),
  支払予定日: z.string().optional(),
  行番号: z.coerce.number(),
  品番: z.string().optional(),
  品名: z.string(),
  数量: z.coerce.number(),
  単位: z.string(),
  '請求金額(税抜)': z.coerce.number(),
  '税率(%)': z.coerce.number().optional(),
  備考: z.string().optional(),
});
